export const autoGeneratedPassword = (passwordLength: number) => {
  const randomIntFromInterval = (min: number, max: number) => {
    return Math.floor(Math.random() * (max - min + 1) + min);
  };

  const randomLetters =
    "1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM!@#$%^&*()";

  let password = "";

  for (let i = 0; i < passwordLength; i++) {
    password =
      password +
      randomLetters[randomIntFromInterval(0, randomLetters.length - 1)];
  }

  return password;
};
