import { prisma } from "../lib/prisma";
import { autoGeneratedPassword } from "../utils/userUtils";

export const createUserModel = async (newUserData: NewUserData) => {
  const { email, username, firstName, lastName } = newUserData;

  if (!email || !username || !firstName || !lastName)
    throw new Error("ValidationError");

  const existing = await prisma.user.findFirst({
    where: { OR: [{ email }, { username }] },
  });
  if (existing?.email === email) throw new Error("EmailAlreadyInUse");
  if (existing?.username === username) throw new Error("UsernameAlreadyTaken");

  const user = await prisma.user.create({
    data: {
      email,
      username,
      firstName,
      lastName,
      password: autoGeneratedPassword(10),
    },
  });

  return user;
};

export const editUserModel = async (editUserData: EditUserData) => {
  const { id, email, username, firstName, lastName } = editUserData;

  if (!email || !username || !firstName || !lastName)
    throw new Error("ValidationError");

  const existingUser = await prisma.user.findUnique({
    where: { id },
  });

  if (!existingUser) throw Error("UserNotFound");

  const existing = await prisma.user.findFirst({
    where: { OR: [{ email }, { username }] },
  });

  if (existing?.email === email && email !== existingUser.email)
    throw new Error("EmailAlreadyInUse");
  if (existing?.username === username && username !== existingUser.username)
    throw new Error("UsernameAlreadyTaken");

  const user = await prisma.user.update({
    where: { id },
    data: { email, username, firstName, lastName },
  });

  return user;
};

export const getUserByEmailModel = async (email: string) => {
  const user = await prisma.user.findUnique({
    where: { email },
  });

  if (!user) throw Error("UserNotFound");

  return user;
};
